### ISSUE TITLE
Scroll up item not show

### ISSUE THREAD

**Issue by duonghb091087** [Arasthel/SpannedGridLayoutManager#34] opened 2018-10-25 15:38 UTC
I select 1,3,5 position. Scroll down, after  slow scroll up item not show. Help me
![screenshot_2018-10-25-22-30-46-561_com arasthel spannedgridlayoutmanager sample](https://user-images.githubusercontent.com/40228807/47512556-a9d0bc00-d8a6-11e8-8f58-fe33f311b436.png)
![Uploading Screenshot_2018-10-25-22-30-41-034_com.arasthel.spannedgridlayoutmanager.sample.png…]()

**Comment by duonghb091087** [comment] 2018-10-25 15:40
![screenshot_2018-10-25-22-30-41-034_com arasthel spannedgridlayoutmanager sample](https://user-images.githubusercontent.com/40228807/47512724-fc11dd00-d8a6-11e8-9875-adfd0ee13b0e.png)

**Comment by Arasthel** [comment] 2018-10-25 20:09
Hi, thanks for reporting. I was just able to reproduce the issue, although I couldn't find a solution so easily... I'll investigate this further.

**Comment by duonghb091087** [comment] 2018-10-26 00:35
> Hi, thanks for reporting. I was just able to reproduce the issue, although I couldn't find a solution so easily... I'll investigate this further.

I will wait your solution. Thanks

**Comment by Arasthel** [comment] 2018-11-12 12:12
This should be fixed in version 3.0.0, since the whole layouting and recycling process was re-written from scratch.

However, this requires a few changes in how you use the library. Make sure to read [the migration section](https://github.com/Arasthel/SpannedGridLayoutManager/#migrating-from-2x-to-3x) on the README.

**Closed by Arasthel** 2018-11-12 12:12 UTC
Labels: bug
